project_id = "rsugotioapwxuelehsml"

[functions.islamic-chatbot]
verify_jwt = false

[functions.crypto-data-fetcher]
verify_jwt = false

[functions.compliance-checker]
verify_jwt = false

[functions.news-sentiment-analyzer]
verify_jwt = false

[functions.portfolio-analyzer]
verify_jwt = false