// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsugotioapwxuelehsml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzdWdvdGlvYXB3eHVlbGVoc21sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1Nzg0OTQsImV4cCI6MjA3MTE1NDQ5NH0._qoXGjLk2SWpoV-VnTKkTicZiOEEs84HZ5QFrTiSAWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});